accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

projects/urls.py
from django.urls import path
from .views import ProjectListView, ProjectDetailView, ProjectCreateView

app_name = "projects"

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:id>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path

from .views import CreateTaskView, MyTasksListView

app_name = "tasks"

urlpatterns = [
    path("create/", CreateTaskView.as_view(), name="create_task"),
    path("mine/", MyTasksListView.as_view(), name="show_my_tasks"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("projects/", include("projects.urls", namespace="projects")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("list-projects/", ProjectListView.as_view(), name="list_projects"),
    path(
        "projects/<int:id>/", ProjectDetailView.as_view(), name="show_project"
    ),
    path(
        "projects/create/", ProjectCreateView.as_view(), name="create_project"
    ),
    path(
        "",
        RedirectView.as_view(
            pattern_name="projects:list_projects", permanent=False
        ),
        name="home",
    ),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="projects", null=True
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from projects.models import Project
from django.contrib.auth.models import User


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        User, null=True, related_name="tasks", on_delete=models.CASCADE
    )

accounts/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)


class SignupForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)
    password_confirmation = forms.CharField(
        max_length=150, widget=forms.PasswordInput
    )

projects/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description", "owner"]

tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ["is_completed"]

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import logout, authenticate, login as auth_login
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from django.urls import reverse
from .forms import LoginForm, SignupForm
from projects.models import Project


@require_http_methods(["GET", "POST"])
def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect(reverse("projects:list_projects"))
            else:
                form.add_error(None, "Invalid username or password.")
    else:
        form = LoginForm()

    return render(request, "accounts/login.html", {"form": form})


@login_required
def list_projects(request):
    projects = Project.objects.filter(members=request.user)
    return render(
        request, "projects/list_projects.html", {"projects": projects}
    )


@login_required
def logout_view(request):
    logout(request)
    return redirect("login")


@require_http_methods(["GET", "POST"])
def signup_view(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]

            if password != password_confirmation:
                form.add_error(
                    "password_confirmation", "The passwords do not match"
                )
                return render(
                    request, "registration/signup.html", {"form": form}
                )

            user = User.objects.create_user(
                username=username, password=password
            )
            auth_login(request, user)
            return redirect(reverse("list_projects"))
    else:
        form = SignupForm()

    return render(request, "registration/signup.html", {"form": form})

projects/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView
from .forms import ProjectForm
from .models import Project


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/project_list.html"
    context_object_name = "projects"

    def get_queryset(self):
        user = self.request.user
        return Project.objects.filter(owner=user)


class ProjectDetailView(LoginRequiredMixin, View):
    def get(self, request, id):
        project = get_object_or_404(Project, id=id)
        return render(
            request, "projects/project_detail.html", {"project": project}
        )


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    form_class = ProjectForm
    template_name = "projects/create_project.html"
    success_url = reverse_lazy("list_projects")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        super().form_valid(form)
        return redirect(self.get_success_url())

tasks/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views import View
from django.views.generic import ListView
from .models import Task

from .forms import TaskForm


class CreateTaskView(LoginRequiredMixin, View):
    login_url = "/login/"
    redirect_field_name = "redirect_to"

    def get(self, request):
        form = TaskForm()
        return render(request, "tasks/create_task.html", {"form": form})

    def post(self, request):
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("projects:list_projects"))

        return render(request, "tasks/create_task.html", {"form": form})


class MyTasksListView(LoginRequiredMixin, ListView):
    login_url = "/login/"
    redirect_field_name = "redirect_to"
    model = Task
    template_name = "tasks/my_tasks.html"
    context_object_name = "tasks"

    def get_queryset(self):
        user = self.request.user
        return Task.objects.filter(assignee=user)

accounts/templates/accounts/login.html
{% extends 'base.html' %} {% block content %}
<main>
  <div>
    <h1>Login</h1>
    <form method="post">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">Login</button>
    </form>
  </div>
</main>
{% endblock %}

accounts/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}Tracker App{% endblock %}</title>
  </head>
  <body>
    <header>
      <nav>
        <ul></ul>
      </nav>
    </header>

    {% block content %}{% endblock %}

    <footer></footer>
  </body>
</html>

projects/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html>
  <head>
    <title>My Project Tracker</title>
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>

projects/templates/projects/create_project.html
{% extends "base.html" %} {% block content %}
<main>
  <div>
    <h1>Create a new project</h1>
    <form method="post">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
</main>
{% endblock %}

projects/templates/projects/project_detail.html
{% extends 'base.html' %} {% block content %}
<main>
  <div>
    <h1>{{ project.name }}</h1>
    <p>{{ project.description }}</p>

    <h2>Tasks</h2>

    {% if project.tasks.exists %}
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Assignee</th>
          <th>Start date</th>
          <th>Due date</th>
          <th>Is completed</th>
        </tr>
      </thead>
      <tbody>
        {% for task in project.tasks.all %}
        <tr>
          <td>{{ task.name }}</td>
          <td>{{ task.assignee.username }}</td>
          <td>{{ task.start_date }}</td>
          <td>{{ task.due_date }}</td>
          <td>{{ task.is_completed|yesno }}</td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="5">No tasks found.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p>This project has no tasks.</p>
    {% endif %}
    <p>
      <a href="{% url 'tasks:create_task' %}">Create a new task</a>
    </p>
  </div>
</main>
{% endblock %}

projects/templates/projects/project_list.html
{% extends 'base.html' %} {% block content %}
<main>
  <div>
    <h1>My Projects</h1>
    <p>
      <a href="{% url 'projects:create_project' %}">Create a new project</a>
    </p>
    {% if projects %}
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Total Tasks</th>
        </tr>
      </thead>
      <tbody>
        {% for project in projects %}
        <tr>
          <td>
            <a href="{% url 'projects:show_project' project.id %}"
              >{{ project.name }}</a
            >
          </td>
          <td>{{ project.tasks.count }}</td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="2">No projects found.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p>You are not assigned to any projects.</p>
    {% endif %}
  </div>
</main>
{% endblock %}

tasks/templates/tasks/create_task.html
{% extends "base.html" %} {% block content %}
<main>
  <div>
    <h1>Create a new task</h1>
    <form method="post">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
</main>
{% endblock %}

tasks/templates/tasks/my_tasks.html
{% extends "base.html" %} {% block content %}
<main>
  <div>
    <h1>My Tasks</h1>
    {% if tasks %}
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Start date</th>
          <th>Due date</th>
          <th>Is completed</th>
        </tr>
      </thead>
      <tbody>
        {% for task in tasks %}
        <tr>
          <td>{{ task.name }}</td>
          <td>{{ task.start_date }}</td>
          <td>{{ task.due_date }}</td>
          <td>{{ task.is_completed|yesno:"yes,no" }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p>You have no tasks</p>
    {% endif %}
  </div>
</main>
{% endblock %}